### ISSUE TITLE
UI is affected by lighting

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#10]
**Describe the bug**
UI elements(Image element at least), is affected by lighting. If a lighting is behind the element it creates shadows and if is in front of it the elements gets iluminated.

**To Reproduce**
1. Create a UI element
2. Create Light 
3. Move the light

**Expected behavior**
UI shouldn't be affected by ingame lights.

**Desktop (please complete the following information):**
 - Engine Version: The Witcher Repository Dev branch 13b3b49 commit

**Comment by PolRecasensSarra** [comment]
I fixed it and now the UI is not afected by lights
