### ISSUE TITLE
Rigidbody

### ISSUE THREAD

**Issue by AlexMG99** [OverPowered-Team/Alien-GameEngine#100]
**Describe the bug**
When I apply a force in a rigidbody doesn't work.

**To Reproduce**
1. Create a GO with a Rigidbody component.
2. Add a script and try to apply a force to the rigidbody.
3. It doesn't work

**Expected behavior**
The rigidbody has to apply a force in the direction of the vector3.

**Versions Information**
 - AlienGameEngine / dev

**Additional context**
I need it in order to create workable arrows

**Person who found the issue**
@AlexMG99

**Comment by AlexMG99** [comment]
It works applying at all time a force, but I need apply and explosive force only at the apply of the force

**Comment by peterMcP** [comment]
works as expected, mass 0 converts the object to static on world physics simulation

**Comment by AlexMG99** [comment]
I need an explosive force that I only call once, nothing to do with the mass (that was another Issue #101). If needs mass, I'll use it, but i'll increment drag avoiding to fall fast.
