### ISSUE TITLE
Rigidbody Mass

### ISSUE THREAD

**Issue by AlexMG99** [OverPowered-Team/Alien-GameEngine#101]
**Describe the bug**
Changing mass doesn't change how the gravity affect the object.

**To Reproduce**
1. Create GO with a component rigidbody.
2. Change mass and click play.
3. The object falls at the same speed even if change mass.

**Expected behavior**
As lower the mass, the slower it fall.

**Comment by peterMcP** [comment]
works as expected. for this functionality, you need to tweak drag (que cae antes, una bala de paja o una de plomo?)
