### ISSUE TITLE
When loading scene there are many possibilities of fonts not loading and not being visible

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#106]
**Describe the bug**
When you stop play or load a scene, there is a great possibility that fonts stop being visible.

**To Reproduce**
1. Load Scene

**Screenshots**
![image](https://user-images.githubusercontent.com/36154682/77847223-aa683300-71bb-11ea-8fb1-94d9841c9a28.png)

**Versions Information**
 - The Witcher Release 28/03

**Comment by AlexMG99** [comment]
It may be a Library problem with fonts. I'll check it later

**Comment by AlexMG99** [comment]
Didn't increase not default fonts references
