### ISSUE TITLE
UI Image doesn't have transparency

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#11]
UI image doen't have transparency in transparent píxels.

**Screenshots**
![image](https://user-images.githubusercontent.com/36154682/75957745-f83e9380-5eba-11ea-9999-d8269f7d90fe.png)
![image](https://user-images.githubusercontent.com/36154682/75957775-07254600-5ebb-11ea-9470-306ad3494452.png)
![image](https://user-images.githubusercontent.com/36154682/75957789-14dacb80-5ebb-11ea-9ced-db78458639fc.png)

**Desktop**
Engine Version: The Witcher Repository Dev branch 2a5ad08 commit

**Comment by PolRecasensSarra** [comment]
Solved UI transparency
