### ISSUE TITLE
'Save as the original' doesn't update other instances of the prefab

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/Alien-GameEngine#118]
**Describe the bug**
I added a script to one instance of the prefab. I pressed 'Save as the original' and then I pressed 'Set as the original' in another. The other prefab doesn't have that script.

**Versions Information**
Repo: TheWitcher
Branch: dev
Commit: 649ba95

**Steps To Reproduce**
1. Go to the specified repo, branch and commit.
2. Drag newTRIGGER.alienScene
3. Open 'Other camera transitions'
4. Select any camera trigger.
5. Open it and select any of the children.
6. Add a 'CameraEnterExit' script.
7. Go to the parent and press 'Save as the original'
8. Go to another instance of the prefab and press 'Set as the original'

**Expected behavior**
The other instance of the prefab also gets the newly added script.

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/78073271-dbee2380-73a0-11ea-992a-b6fa52d9b166.png)

**Additional context**
Right now all the CameraTrigger prefabs have lost this change due to updates on the engine and script. Going one by one adding the script is a huge loss of time.

**Comment by OriolCS2** [comment]
Jaume thas equivocat

**Comment by OriolCS2** [comment]
Fixet qui es el prefab root, es el que te tots els camera triggers

**Comment by OriolCS2** [comment]
No tenim prefabs dins prefabs obviament jajaja

**Comment by OriolCS2** [comment]
Tanco
