### ISSUE TITLE
Show different fields on the inspector depending on a selected enum or bool

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/Alien-GameEngine#120]
**Is your feature request related to a problem? Please describe.**
This could help clear things out in the inspector, for scripts such as the camera where not all parameters are needed for some types of cameras.

**Describe the solution you'd like**
When you change the selected enum, only the fields that you need to configure are shown.

**Additional context**
This is how Unity handles it.

![image](https://user-images.githubusercontent.com/36292291/78468257-5b1f8680-7716-11ea-8dc2-b886799b5060.png)
![image](https://user-images.githubusercontent.com/36292291/78468260-64a8ee80-7716-11ea-9302-f3869d0e997c.png)

**Comment by OriolCS2** [comment]
Ja es va fer una issue daixo i no es fara
