### ISSUE TITLE
ComponentText doesn't update its alpha

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#130]
**Describe the bug**
ComponentText doesn't update its alpha. In addition, it has no function SetColor in Scripting, only BackgroundColor that doesn't affect it.

**Expected behavior**
It should respect its alpha.

**Comment by AlexMG99** [comment]
Solved. Changing alpha now works. Important to CHANGE THE SHADER in The Witcher (I'll do it now).
SetBackgroundColor worked fine. Anyways, added two functions: SetColor and SetAlpha if you want to change one or another
