### ISSUE TITLE
MATERIAL -> CRASH WHEN CLOSING ENGINE 

### ISSUE THREAD

**Issue by PolRecasensSarra** [OverPowered-Team/Alien-GameEngine#15]
**Describe the bug**
The engine crash when you close it. It is related to Materials. Also, the default material gone empty when closing the engine and you need to copy and paste an older default material.material

![materialBug](https://user-images.githubusercontent.com/36154612/76340476-f0885000-62fb-11ea-9ef3-e07fc2e94613.png)

**Comment by Sebi-Lopez** [comment]
How do I reproduce it?

**Comment by Sebi-Lopez** [comment]
was fixed! 💥
