### ISSUE TITLE
Bug With Animation With No Loop

### ISSUE THREAD

**Issue by lakaens** [OverPowered-Team/Alien-GameEngine#17]
**Describe the bug**
If a model is incorporated into the engine which has no loop, the animation crashes.

**To Reproduce**
Drag an fbx with animation (mixamo for example) to the engine, do not activate the loop option since it does not have, and when configuring the animator with a single animation it is appreciated in the scene or game modes that the animation when completing a iteration crashes.

**Expected behavior**
Just do an iteration because it has no loop and stay still or do the action that's ment to be without crashing.

**Screenshots**

**Versions Information**
 - Dev Branch

**Person who found the issue**
 Eric Navarro

**Comment by CereVenteo** [comment]
It is because mixamo has the last frame empty sometimes, but it will stay like this I think.
