### ISSUE TITLE
PHYSICS: Capsule Collider height doesn't edit the GameObject height correctly

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#20]
**Describe the bug**
Bug 1: When you try to edit the capsule collider height through the Game Object, the capsule collider height tends to infinity very quickly and doesn't edit correctly:
https://i.gyazo.com/0f54ceae5702e199065138150e5b4432.mp4

**To Reproduce**
1. Create GameObject
2. Add Capsule Collider
3. Edit Height

**Expected behavior**
Should edit the height in the same way other colliders do.

**Versions Information**
 - Dev Branch
 - Commit 00798135

**Person who found the issue**
  - Víctor Segura

**Comment by peterMcP** [comment]
works correctly now
