### ISSUE TITLE
PHYSICS: Capsule Collider Height doesn't update

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#23]
**Describe the bug**
If you edit the height of the capsule collider, it doesn't update.

**To Reproduce**
1. Create Game Object
2. Add Capsule Collider Component
3. Edit Height in its inspector

**Expected behavior**
The height should update like in the inspector

**Screenshots**
https://i.gyazo.com/01e3319c059c67b2a10bf7ff918bee2d.mp4

**Versions Information**
 - Branch Dev
 - Commit 00798135

**Person who found the issue**
 - Víctor Segura

**Comment by peterMcP** [comment]
works correctly now
