### ISSUE TITLE
PHYSICS: Rigidbody can't be deleted or disabled

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#24]
**Describe the bug**
Rigidbody can't be deleted or disabled

**To Reproduce**
1. Create GameObject
2. Add RigidBody Component
3. Try to remove it

**Expected behavior**
The user should be able to remove it

**Versions Information**
 - Branch Dev 
 - Commit 00798135

**Comment by peterMcP** [comment]
now can be deleted, disable is other issue
