### ISSUE TITLE
Add Title, Separators and help markers in inspector scripts

### ISSUE THREAD

**Issue by christt105** [OverPowered-Team/Alien-GameEngine#27]
**Describe the solution you'd like**
It could help if there are options to put a title (just a constant string) between vars. Also, a ImGui::Separator() will make the inspector more readable when we have more variables in inspector. In order to the designer know more of what makes that variables inside the code, a helper text can be shown when hover the var name.

**Comment by OriolCS2** [comment]
Think it's done 💯
