### ISSUE TITLE
Fonts don't load correctly when in game mode

### ISSUE THREAD

**Issue by RoperoIvan** [OverPowered-Team/Alien-GameEngine#3]
**Describe the bug**
When the engine is in game mode the fonts don't load correctly and the engine crashes.

**To Reproduce**
1. Do a build
2. Execute the build (exe)

**Expected behavior**
It shouldn't broke the game.

**Screenshots**
It brokes.

**Desktop (please complete the following information):**
 - Version 1.0

**Additional context**

**Comment by AlexMG99** [comment]
It seems to be that font doesn't not save well or doesn't load correctly

**Comment by AlexMG99** [comment]
In theory, after applying glPixelStorei(GL_UNPACK_ALIGNMENT, 1); // Disable byte-alignment restriction
everythin is working fine
