### ISSUE TITLE
Box collider scale gizmo does not work

### ISSUE THREAD

**Issue by AlbertCayuela** [OverPowered-Team/Alien-GameEngine#31]
**Describe the bug**
If you create a box collider and you try to scale it using the gizmos, the scale turns into 0.

**To Reproduce**
1. Create a GameObject
2. Add Box Collider Component
3. Try to change the scale using the gizmos

**Expected behavior**
It should change the scale properly when using the gizmos

**Versions Information**
 - Branch Dev

**Person who found the issue**
Albert Cayuela
 
Add the person who found the issue in order to know who to talk to if the coder in charge   of solving the issue has any doubt.

**Comment by peterMcP** [comment]
works correctly now
