### ISSUE TITLE
Texture bug with particle system

### ISSUE THREAD

**Issue by lakaens** [OverPowered-Team/Alien-GameEngine#32]
**Describe the bug**
When you have more than one particle emitter in the scene and one of those particle emitter have a material with a texture, when you select in the hierarchy another particle emitter, the texture of the first one disappears.

**To Reproduce**
 1. Create a first particle emitter with a material and texture
 2. Create two more particle emitters.
 3. Go back to the first emitter and you will see that doesn't have the texture previously asigned to the material.

**Expected behavior**
The texture assigned to the material doesn't dissapears.

**Versions Information**
 - Dev

**Person who found the issue**
 
Eric Navarro

**Comment by CarlosUPC** [comment]
bug is not displayed following the steps. It seems like an ambiguous issue which needs a reformulation. Closed for now.
