### ISSUE TITLE
Gizmo does not have color

### ISSUE THREAD

**Issue by christt105** [OverPowered-Team/Alien-GameEngine#34]
**Describe the bug**
Gizmo does not have color.

**Expected behavior**
Gizmos with color.

**Screenshots**
![image](https://user-images.githubusercontent.com/36189169/76863584-fb913200-685f-11ea-852d-264843b05374.png)

**Versions Information**
 - 1.0

**Person who found the issue**
@christt105 
 
Add the person who found the issue in order to know who to talk to if the coder in charge   of solving the issue has any doubt.

**Comment by OriolCS2** [comment]
Fixed in dev alien engine
