### ISSUE TITLE
Changing the material of the mesh when you add a Particle System to the same object

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/Alien-GameEngine#36]
**Describe the bug**
When you add a particle system to an object that has a mesh, it changes the material of the mesh.

**To Reproduce**
1. Create a gameobject (for example a Rock).
2. Add particle system component.

**Expected behavior**
The mesh stays with the same material.

**Screenshots**
![bug](https://user-images.githubusercontent.com/36292291/76889747-72d9bc80-6886-11ea-9943-8d270a0aa573.png)

**Person who found the issue**
- Jaume Montagut

**Comment by JaumeMontagut** [comment]
After that, when you create any rock they appear with the 'particle_shader' by default.

**Comment by CarlosUPC** [comment]
bug currently fixed in issue #54
