### ISSUE TITLE
Faster search through components

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/Alien-GameEngine#40]
**Is your feature request related to a problem? Please describe.**
It takes a long time to look for a specific component in the list of components.

**Describe the solution you'd like**
The list of components (and also scripts) are ordered alphabetically. If you press a key, you scroll down to the first component starting with that letter.
For inspiration, look at windows explorers.

**Describe alternatives you've considered**
Work like Unity, you have a field where you can write the name of the component and it only shows the ones containing those letters.

**Comment by AlexMG99** [comment]
We ordered alphabetically
