### ISSUE TITLE
Engine crashes after deleting button

### ISSUE THREAD

**Issue by AlbertCayuela** [OverPowered-Team/Alien-GameEngine#45]
**Describe the bug**
When you try to delete a button after pressing play, the engine crashes.

**To Reproduce**
1. Create a button
2. Click on the play button
3. Press again the play button (stop the game)
4. Delete the button from de inspector
5. See error

**Expected behavior**
The button should be deleted normally

**Versions Information**
 - Branch Dev

**Person who found the issue**
Albert Cayuela
 
Add the person who found the issue in order to know who to talk to if the coder in charge   of solving the issue has any doubt.

**Comment by PolRecasensSarra** [comment]
Bug solved. I made a mistake by non checking if the gameobject has a componentUI when executing Focus functions
