### ISSUE TITLE
PHYSICS: When you have more than one collider, all move together

### ISSUE THREAD

**Issue by CereVenteo** [OverPowered-Team/Alien-GameEngine#47]
**Describe the bug**
When change Character Controller Offset, the Box Collider Center changes too.

**To Reproduce**
1. Create a Character Controller
2. Create a Box Collider
3. Change Character Controller Offset or Box Collider Center

**Expected behavior**

**Screenshots**
![collider](https://user-images.githubusercontent.com/36203330/76983416-aa577000-693d-11ea-82a8-ab46cb4155a7.png)

**Person who found the issue**
Cere Venteo

**Comment by peterMcP** [comment]
works correctly now, (imgui ID conflicts)
