### ISSUE TITLE
Saving Inspector Scripts: Variables with same name from inspector

### ISSUE THREAD

**Issue by peterMcP** [OverPowered-Team/Alien-GameEngine#50]
**Describe the bug**
When we have variables from scripts with same name in inspector from same structure type (same members, with same names), saving/load or playing/stop the scene only saves the first ones.

**To Reproduce**
1. Go to commit https://github.com/OverPowered-Team/TheWitcher/commit/e31e07fd451f761c7759297bc971cf5e4a8b9ef9
2. Load test_camera.alienscene
3. Go to CameraTrigger gameobject.
4. Check and play with TriggerCameraScript (play/stop), and checks how loads bad values

**Expected behavior**
All fields from same structure type with saved values remains the same which we type in inspector

**Versions Information**
 - all versions

**Screenshot**

![image](https://user-images.githubusercontent.com/36275626/77030305-72344980-699e-11ea-9edd-c160795c4bb6.png)

**Comment by OriolCS2** [comment]
Fixed!
