### ISSUE TITLE
Inspector Scripts: ctrl+z not restoring values

### ISSUE THREAD

**Issue by peterMcP** [OverPowered-Team/Alien-GameEngine#51]
**Describe the bug**
When we delete a gameobject with component script with any value attached to it, delete it and restoring with ctrl+z wipe out all values.

**To Reproduce**
1. Add a gameobject
2. Attach any script with values
3. Delete gameobject
4. undo delete with ctrl+z
5. All values are wiped

**Expected behavior**
Restore the gameobject with last values present on the script

**Versions Information**
 - all versions

**Comment by OriolCS2** [comment]
La tanco, el cntrl z no esta posat a rea nou aixi que no te sentit posarlo aqui
