### ISSUE TITLE
Duplicate gameobjects not mantain the scale

### ISSUE THREAD

**Issue by peterMcP** [OverPowered-Team/Alien-GameEngine#52]
**Describe the bug**
When we duplicate any gameobject with mesh not mantain the scale from its source object

**To Reproduce**
1. Create primitive cube
2. Scale the cube
3. Duplicate the object

**Expected behavior**
Duplicated object with same size as the source

**Versions Information**
 - all versions (18/03/2020)
- (last)https://github.com/OverPowered-Team/Alien-GameEngine/tree/effff79dd389c92b9542c4445d098788933f39c6

**Comment by OriolCS2** [comment]
closed
https://gyazo.com/9a945dcce7031be8d3dd1a82f7a377de
