### ISSUE TITLE
Default material changes default shader

### ISSUE THREAD

**Issue by Sebi-Lopez** [OverPowered-Team/Alien-GameEngine#54]
**Describe the bug**
Default material appears to be with particle shader 

**To Reproduce**
It is related to applying particles material

**Expected behavior**
Default material should always have default shader

**Comment by Sebi-Lopez** [comment]
It's caused cause the default material pointer is modified by the particle system 
![image](https://user-images.githubusercontent.com/36292214/77122809-dd355d00-6a3e-11ea-8d31-ae89a1f6667a.png)

**Comment by CarlosUPC** [comment]
fixed
