### ISSUE TITLE
Bug: Tarda mucho en cerrarse y salta el mensaje de programa no responde

### ISSUE THREAD

**Issue by YessicaSD** [OverPowered-Team/Alien-GameEngine#55]
**Describe the bug**
Al cerrar el programa, puede llegar a saltar el mensaje de el programa no responde.

**To Reproduce**
1. Click several times to exit button 

**Screenshots**
![Bug](https://user-images.githubusercontent.com/36170847/77103508-cda41d00-6a1a-11ea-989d-cf3fc9c39bc4.PNG)

**Versions Information**
Release v0.2.0

**Person who found the issue**
 -Yessica Servin

**Comment by OriolCS2** [comment]
close
