### ISSUE TITLE
Prefabs lose connection (id problem)

### ISSUE THREAD

**Issue by peterMcP** [OverPowered-Team/Alien-GameEngine#66]
**Describe the bug**
Prefabs lose connection with scripts with gameobject on inspector (id problem)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions Information**
 - Branch / Release 
 - Commit Number (if checking in repository, not in release)

**Additional context**

**Person who found the issue**
 
Add the person who found the issue in order to know who to talk to if the coder in charge   of solving the issue has any doubt.

**Comment by OriolCS2** [comment]
Done
