### ISSUE TITLE
[REQUEST] Multiselect and add component

### ISSUE THREAD

**Issue by JaumeMontagut** [OverPowered-Team/Alien-GameEngine#8]
**Is your feature request related to a problem? Please describe.**
We'd like to be able to add colliders to all the selected gameobjects at the same time, not one by one.

**Describe the solution you'd like**
When selecting mutliple objects, and going to the hierarchy and adding a component, it gets added to all selected gameobjects.

**Additional context**
It could also save time in other areas such as when adding scripts to a group of gameobjects.

**Comment by OriolCS2** [comment]
close 
https://gyazo.com/d4cbf1f0d097d57298b1bc6003defe0c
