### ISSUE TITLE
Activate/Deactivate Navigation from a Canvas through Scripting

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#88]
**Is your feature request related to a problem? Please describe.**
When open Settings/Controls menus(menus you can access from more than one scene), we need another canvas in the scene. So it's needed that we can choose the canvas that gets the navigation input.

**Comment by PolRecasensSarra** [comment]
I have created a variable called allow_navigation (it's from ComponentCanvas). If you set it to false, navigation will not be done on that canvas. Also, if you are navigating a canvas and you deny the navigation, you will need to call ResetFocusUI (ModuleObjects.cpp). This will reset navigation and select the first canvas in the hierarchy that allows navigation. I recommend calling ResetFocusUI every time you set "allow_navigation" to false
