### ISSUE TITLE
Canvas prints with Scene rotation in game

### ISSUE THREAD

**Issue by VictorSegura99** [OverPowered-Team/Alien-GameEngine#9]
When create a canvas and go to game, the canvas borders get printed with the rotation from the scene camera.
![image](https://user-images.githubusercontent.com/36154682/75902260-0a2f2080-5e40-11ea-92a4-0357c1d209cd.png)

1. Create a Canvas
2. Go to Game Panel

Engine Version: The Witcher Repository Dev branch 13b3b49 commit

**Comment by PolRecasensSarra** [comment]
Issue solved by AlexMG99
